@api = http://localhost:4445/api
@sessionId = f3191f88-dfaf-4217-814f-a67e934b8cea
@proxyPort = 61739

###

PUT {{api}}/proxies/{{sessionId}}/inject
content-type: application/json

{
        "uri":"api/foobar",
        "response":{
               "content":"Hello World" 
        },
        "statusCode":""
}

